"""KPI cards, evidence cards, recommendation cards with provenance badges.

Enhanced with tooltips, provenance variants, freshness indicators,
alert cards, and loading skeleton support for industrial dark UI.
"""
from __future__ import annotations

import streamlit as st

# ── Design tokens (matches app.py industrial dark theme) ────────────────────
CARD_BG = "#111827"
CARD_BORDER = "#1F2937"
TEXT_PRIMARY = "#F9FAFB"
TEXT_SECONDARY = "#9CA3AF"
ACCENT = "#3B82F6"
SUCCESS = "#10B981"
WARNING = "#F59E0B"
DANGER = "#EF4444"
SHADOW = "0 4px 6px -1px rgba(0,0,0,0.45), 0 2px 4px -2px rgba(0,0,0,0.35)"

STATE_COLORS = {
    "HEALTHY": SUCCESS,
    "WATCH": WARNING,
    "DEGRADING": "#F97316",
    "CRITICAL": DANGER,
    "FAILURE-LIKELY": "#991B1B",
}

PROVENANCE_COLORS = {
    "OBSERVED": ACCENT,
    "PREDICTED": WARNING,
    "SIMULATED": "#8B5CF6",
}

PROVENANCE_TOOLTIPS = {
    "OBSERVED": "Directly measured from sensor telemetry",
    "PREDICTED": "Generated by the ML model (not yet observed)",
    "SIMULATED": "Model-based what-if analysis — not a real operational outcome",
}

SEVERITY_COLORS = {
    "info": ACCENT,
    "warning": WARNING,
    "danger": DANGER,
    "success": SUCCESS,
}


def _badge(label: str, bg: str, fg: str = "#FFFFFF") -> str:
    return (
        f'<span style="background:{bg};color:{fg};padding:2px 8px;'
        f'border-radius:4px;font-size:0.72rem;font-weight:600;'
        f'letter-spacing:0.4px;">{label}</span>'
    )


def _tooltip(text: str) -> str:
    """Wrap text in a tooltip span."""
    return (
        f'<span class="st-tooltip-wrapper">{text}'
        f'<span class="st-tooltip-text">{text}</span></span>'
    )


def state_badge(state: str) -> str:
    colour = STATE_COLORS.get(state.upper(), "#4B5563")
    return _badge(state.upper(), colour)


def provenance_badge(kind: str, with_tooltip: bool = True) -> str:
    """Provenance badge with optional tooltip explaining the type."""
    colour = PROVENANCE_COLORS.get(kind.upper(), "#4B5563")
    label = kind.upper()
    if with_tooltip and label in PROVENANCE_TOOLTIPS:
        tooltip_text = PROVENANCE_TOOLTIPS[label]
        return (
            f'<span class="st-tooltip-wrapper prov-{label.lower()}" '
            f'style="display:inline-block;background:{colour}22;color:{colour};'
            f'padding:2px 8px;border-radius:4px;font-size:0.72rem;font-weight:600;'
            f'letter-spacing:0.4px;">{label}'
            f'<span class="st-tooltip-text">{tooltip_text}</span></span>'
        )
    return _badge(label, colour)


def freshness_indicator(updated_seconds_ago: float | None = None) -> str:
    """Render a pulsing freshness dot with timestamp."""
    if updated_seconds_ago is None:
        dot_cls = "st-freshness-dot st-freshness-ok"
        label = "Live"
    elif updated_seconds_ago < 30:
        dot_cls = "st-freshness-dot st-freshness-ok"
        label = f"{updated_seconds_ago:.0f}s ago"
    elif updated_seconds_ago < 300:
        dot_cls = "st-freshness-dot st-freshness-stale"
        label = f"{updated_seconds_ago:.0f}s ago (stale)"
    else:
        dot_cls = "st-freshness-dot st-freshness-stale"
        label = f"{updated_seconds_ago / 60:.1f}m ago (stale)"
    return (
        f'<span class="st-freshness"><span class="{dot_cls}"></span>{label}</span>'
    )


def kpi_card(
    label: str,
    value: str | float | int,
    *,
    delta: str | None = None,
    delta_color: str = "normal",
    provenance: str | None = None,
    tooltip: str | None = None,
):
    """Render a KPI metric card with optional tooltip and provenance."""
    prov_html = f" {provenance_badge(provenance)}" if provenance else ""
    label_html = _tooltip(label) if tooltip else label
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border:1px solid {CARD_BORDER}; border-radius:10px;
            padding:16px 18px; margin-bottom:12px; box-shadow:{SHADOW};
        ">
            <div style="font-size:0.72rem; color:{TEXT_SECONDARY}; text-transform:uppercase;
                        letter-spacing:1px; margin-bottom:6px; font-weight:600;">
                {label_html}{prov_html}
            </div>
            <div style="font-size:1.6rem; font-weight:700; color:{TEXT_PRIMARY};
                        font-family:'JetBrains Mono','Fira Code',monospace;">
                {value}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if delta:
        st.caption(delta)


def evidence_card(
    title: str,
    body: str,
    *,
    sensor: str | None = None,
    provenance: str = "OBSERVED",
    severity: str = "info",
):
    """Evidence card with provenance badge and severity indicator."""
    border = SEVERITY_COLORS.get(severity, CARD_BORDER)
    sensor_html = (
        f'<span style="color:{TEXT_SECONDARY};font-size:0.72rem;"> | {sensor}</span>'
        if sensor else ""
    )
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border-left:3px solid {border};
            border-radius:0 8px 8px 0; padding:12px 16px; margin-bottom:10px;
            box-shadow:{SHADOW};
        ">
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:4px;">
                <span style="font-weight:600; color:{TEXT_PRIMARY}; font-size:0.88rem;">
                    {title}
                </span>
                {provenance_badge(provenance)}
                {sensor_html}
            </div>
            <div style="color:{TEXT_SECONDARY}; font-size:0.82rem; line-height:1.45;">
                {body}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def recommendation_card(
    text: str,
    *,
    priority: str = "medium",
    provenance: str = "PREDICTED",
):
    """Actionable recommendation card with priority and provenance."""
    prio_colors = {
        "high": DANGER,
        "medium": WARNING,
        "low": SUCCESS,
    }
    border = prio_colors.get(priority, ACCENT)
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border-left:3px solid {border};
            border-radius:0 8px 8px 0; padding:12px 16px; margin-bottom:10px;
            box-shadow:{SHADOW};
        ">
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:4px;">
                <span style="font-weight:600; color:{TEXT_PRIMARY}; font-size:0.88rem;">
                    Recommendation
                </span>
                {_badge(priority.upper(), border)}
                {provenance_badge(provenance)}
            </div>
            <div style="color:{TEXT_SECONDARY}; font-size:0.82rem; line-height:1.45;">
                {text}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def delta_card(label: str, original: float, simulated: float, *, fmt: str = ".3f"):
    """Show original → simulated with color-coded delta."""
    delta = simulated - original
    sign = "+" if delta >= 0 else ""
    colour = DANGER if delta < 0 else SUCCESS
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border:1px solid {CARD_BORDER}; border-radius:10px;
            padding:14px 16px; margin-bottom:10px; box-shadow:{SHADOW};
        ">
            <div style="font-size:0.72rem; color:{TEXT_SECONDARY}; text-transform:uppercase;
                        letter-spacing:0.8px; margin-bottom:6px; font-weight:600;">{label}</div>
            <div style="display:flex; align-items:baseline; gap:10px;">
                <span style="font-size:1.1rem; color:{TEXT_PRIMARY};
                             font-family:'JetBrains Mono',monospace;">
                    {original:{fmt}}
                </span>
                <span class="st-compare-arrow">→</span>
                <span style="font-size:1.1rem; color:{TEXT_PRIMARY};
                             font-family:'JetBrains Mono',monospace;">
                    {simulated:{fmt}}
                </span>
                <span style="font-size:0.85rem; font-weight:600; color:{colour};">
                    ({sign}{delta:{fmt}})
                </span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def alert_card(
    title: str,
    message: str,
    *,
    severity: str = "warning",
    icon: str = "⚠️",
):
    """Severity-scored alert card with icon and color strip."""
    border = SEVERITY_COLORS.get(severity, CARD_BORDER)
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border-left:3px solid {border};
            border-radius:0 8px 8px 0; padding:12px 16px; margin-bottom:10px;
            box-shadow:{SHADOW};
        ">
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:4px;">
                <span style="font-size:1rem;">{icon}</span>
                <span style="font-weight:600; color:{TEXT_PRIMARY}; font-size:0.88rem;">
                    {title}
                </span>
                {_badge(severity.upper(), border)}
            </div>
            <div style="color:{TEXT_SECONDARY}; font-size:0.82rem; line-height:1.45;">
                {message}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def progress_card(label: str, current: float, maximum: float = 100.0, *, suffix: str = ""):
    """RUL countdown or progress bar card."""
    pct = min(current / maximum, 1.0) if maximum > 0 else 0.0
    bar_color = SUCCESS if pct > 0.5 else WARNING if pct > 0.2 else DANGER
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border:1px solid {CARD_BORDER}; border-radius:10px;
            padding:14px 18px; margin-bottom:12px; box-shadow:{SHADOW};
        ">
            <div style="font-size:0.72rem; color:{TEXT_SECONDARY}; text-transform:uppercase;
                        letter-spacing:1px; margin-bottom:8px; font-weight:600;">{label}</div>
            <div style="font-size:1.4rem; font-weight:700; color:{TEXT_PRIMARY};
                        font-family:'JetBrains Mono',monospace; margin-bottom:8px;">
                {current:.1f}{suffix}
            </div>
            <div style="background:#1a2236;border-radius:4px;height:6px;overflow:hidden;">
                <div style="background:{bar_color};width:{pct * 100:.1f}%;height:100%;
                            border-radius:4px;transition:width 0.3s ease;"></div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def disclaimer_banner(text: str = "SIMULATION — not real operational data"):
    """Persistent simulation disclaimer with violet accent."""
    st.markdown(
        f"""
        <div style="
            background:rgba(139,92,246,0.12); border:1px solid #8B5CF6;
            border-radius:8px; padding:10px 16px; margin-bottom:14px;
            color:{TEXT_PRIMARY}; font-size:0.82rem; text-align:center;
            font-weight:600; letter-spacing:0.4px;">
            ⚠ {text}
        </div>
        """,
        unsafe_allow_html=True,
    )


def section_header(title: str, subtitle: str = ""):
    """Section header with optional subtitle."""
    sub_html = (
        f'<span style="color:{TEXT_SECONDARY};font-size:0.82rem;margin-left:8px;">{subtitle}</span>'
        if subtitle else ""
    )
    st.markdown(
        f'<h3 style="color:{TEXT_PRIMARY};margin-bottom:4px;">{title}{sub_html}</h3>',
        unsafe_allow_html=True,
    )
    st.markdown("---")


def skeleton_card():
    """Loading skeleton placeholder for async data."""
    st.markdown(
        '<div class="st-skeleton"></div>',
        unsafe_allow_html=True,
    )
