"""KPI cards, evidence cards, recommendation cards with provenance badges.

Enhanced with tooltips, provenance variants, freshness indicators,
alert cards, and loading skeleton support for industrial dark UI.
"""
from __future__ import annotations

import streamlit as st

from stattwin.dashboard.components.theme import (
    ACCENT,
    BORDER,
    CARD,
    DANGER,
    MONO,
    MUTED,
    PROVENANCE_COLORS,
    SHADOW,
    STATE_COLORS,
    SUCCESS,
    TEXT,
    WARNING,
)

__all__ = [
    "CARD_BG",
    "CARD_BORDER",
    "TEXT_PRIMARY",
    "TEXT_SECONDARY",
    "SHADOW",
    "STATE_COLORS",
    "PROVENANCE_COLORS",
    "state_badge",
    "provenance_badge",
    "freshness_indicator",
    "kpi_card",
    "evidence_card",
    "recommendation_card",
    "delta_card",
    "alert_card",
    "progress_card",
    "disclaimer_banner",
    "section_header",
    "page_header",
    "skeleton_card",
]

# Back-compat aliases (older views import these names)
CARD_BG = CARD
CARD_BORDER = BORDER
TEXT_PRIMARY = TEXT
TEXT_SECONDARY = MUTED
SHADOW = SHADOW

PROVENANCE_TOOLTIPS = {
    "OBSERVED": "Directly measured from sensor telemetry",
    "PREDICTED": "Generated by the ML model (not yet observed)",
    "SIMULATED": "Model-based what-if analysis — not a real operational outcome",
}

SEVERITY_COLORS = {
    "info": ACCENT,
    "warning": WARNING,
    "danger": DANGER,
    "success": SUCCESS,
}


def _badge(label: str, bg: str, fg: str = "#FFFFFF") -> str:
    return (
        f'<span class="st-badge" style="background:{bg};color:{fg};'
        f'border-color:{bg}55;">{label}</span>'
    )


def _tooltip(text: str) -> str:
    """Wrap text in a tooltip span."""
    return (
        f'<span class="st-tooltip-wrapper">{text}'
        f'<span class="st-tooltip-text">{text}</span></span>'
    )


def state_badge(state: str) -> str:
    colour = STATE_COLORS.get(state.upper(), "#4B5563")
    return _badge(state.upper(), colour)


def provenance_badge(kind: str, with_tooltip: bool = True) -> str:
    """Provenance badge with optional tooltip explaining the type."""
    colour = PROVENANCE_COLORS.get(kind.upper(), "#4B5563")
    label = kind.upper()
    if with_tooltip and label in PROVENANCE_TOOLTIPS:
        tooltip_text = PROVENANCE_TOOLTIPS[label]
        return (
            f'<span class="st-tooltip-wrapper prov-{label.lower()}" '
            f'style="display:inline-block;background:{colour}22;color:{colour};'
            f'padding:2px 8px;border-radius:4px;font-size:0.72rem;font-weight:600;'
            f'letter-spacing:0.4px;">{label}'
            f'<span class="st-tooltip-text">{tooltip_text}</span></span>'
        )
    return _badge(label, colour)


def freshness_indicator(updated_seconds_ago: float | None = None) -> str:
    """Render a pulsing freshness dot with timestamp."""
    if updated_seconds_ago is None:
        dot_cls = "st-freshness-dot st-freshness-ok"
        label = "Live"
    elif updated_seconds_ago < 30:
        dot_cls = "st-freshness-dot st-freshness-ok"
        label = f"{updated_seconds_ago:.0f}s ago"
    elif updated_seconds_ago < 300:
        dot_cls = "st-freshness-dot st-freshness-stale"
        label = f"{updated_seconds_ago:.0f}s ago (stale)"
    else:
        dot_cls = "st-freshness-dot st-freshness-stale"
        label = f"{updated_seconds_ago / 60:.1f}m ago (stale)"
    return (
        f'<span class="st-freshness"><span class="{dot_cls}"></span>{label}</span>'
    )


def kpi_card(
    label: str,
    value: str | float | int,
    *,
    delta: str | None = None,
    delta_color: str = "normal",
    provenance: str | None = None,
    tooltip: str | None = None,
):
    """Render a KPI metric card with optional tooltip and provenance."""
    prov_html = f" {provenance_badge(provenance)}" if provenance else ""
    label_html = _tooltip(label) if tooltip else label
    delta_html = f'<div class="st-kpi-delta">{delta}</div>' if delta else ""
    st.markdown(
        f"""
        <div class="st-kpi">
            <div class="st-kpi-label">{label_html}{prov_html}</div>
            <div class="st-kpi-value">{value}</div>
            {delta_html}
        </div>
        """,
        unsafe_allow_html=True,
    )


def evidence_card(
    title: str,
    body: str,
    *,
    sensor: str | None = None,
    provenance: str = "OBSERVED",
    severity: str = "info",
):
    """Evidence card with provenance badge and severity indicator."""
    border = SEVERITY_COLORS.get(severity, CARD_BORDER)
    sensor_html = (
        f'<span style="color:{MUTED};font-size:0.72rem;font-family:{MONO};"> · {sensor}</span>'
        if sensor
        else ""
    )
    st.markdown(
        f"""
        <div class="st-card" style="border-left:3px solid {border};">
            <div style="display:flex; align-items:center; gap:8px;
                        margin-bottom:5px; flex-wrap:wrap;">
                <span style="font-weight:650; color:{TEXT}; font-size:0.9rem;">{title}</span>
                {provenance_badge(provenance)}
                {sensor_html}
            </div>
            <div style="color:{MUTED}; font-size:0.84rem; line-height:1.5;">{body}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def recommendation_card(
    text: str,
    *,
    priority: str = "medium",
    provenance: str = "PREDICTED",
):
    """Actionable recommendation card with priority and provenance."""
    prio_colors = {"high": DANGER, "medium": WARNING, "low": SUCCESS}
    border = prio_colors.get(priority, ACCENT)
    st.markdown(
        f"""
        <div class="st-card" style="border-left:3px solid {border};">
            <div style="display:flex; align-items:center; gap:8px;
                        margin-bottom:5px; flex-wrap:wrap;">
                <span style="font-weight:650; color:{TEXT}; font-size:0.9rem;">Recommendation</span>
                {_badge(priority.upper(), border)}
                {provenance_badge(provenance)}
            </div>
            <div style="color:{MUTED}; font-size:0.84rem; line-height:1.5;">{text}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def delta_card(
    label: str,
    original: float,
    simulated: float,
    *,
    fmt: str = ".3f",
    higher_is_better: bool = True,
    provenance: str = "SIMULATED",
):
    """Show original → simulated with color-coded delta.

    ``higher_is_better`` controls delta colour: green when the change is
    favourable (e.g. higher SHI / higher RUL, or lower risk metrics when
    set to ``False``).
    """
    delta = simulated - original
    sign = "+" if delta >= 0 else ""
    if abs(delta) < 1e-15:
        colour = MUTED
    elif (delta > 0) == higher_is_better:
        colour = SUCCESS
    else:
        colour = DANGER
    prov_html = f" {provenance_badge(provenance)}" if provenance else ""
    st.markdown(
        f"""
        <div class="st-kpi">
            <div class="st-kpi-label">{label}{prov_html}</div>
            <div style="display:flex; align-items:baseline; gap:10px; flex-wrap:wrap;">
                <span class="st-kpi-value" style="font-size:1.1rem;">{original:{fmt}}</span>
                <span style="color:{MUTED};">→</span>
                <span class="st-kpi-value" style="font-size:1.1rem;">{simulated:{fmt}}</span>
                <span style="font-size:0.82rem; font-weight:700; color:{colour};
                             font-family:'JetBrains Mono',monospace;">
                    ({sign}{delta:{fmt}})
                </span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def alert_card(
    title: str,
    message: str,
    *,
    severity: str = "warning",
    icon: str = "⚠️",
):
    """Severity-scored alert card with icon and color strip."""
    border = SEVERITY_COLORS.get(severity, CARD_BORDER)
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border-left:3px solid {border};
            border-radius:0 8px 8px 0; padding:12px 16px; margin-bottom:10px;
            box-shadow:{SHADOW};
        ">
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:4px;">
                <span style="font-size:1rem;">{icon}</span>
                <span style="font-weight:600; color:{TEXT_PRIMARY}; font-size:0.88rem;">
                    {title}
                </span>
                {_badge(severity.upper(), border)}
            </div>
            <div style="color:{TEXT_SECONDARY}; font-size:0.82rem; line-height:1.45;">
                {message}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def progress_card(label: str, current: float, maximum: float = 100.0, *, suffix: str = ""):
    """RUL countdown or progress bar card."""
    pct = min(current / maximum, 1.0) if maximum > 0 else 0.0
    bar_color = SUCCESS if pct > 0.5 else WARNING if pct > 0.2 else DANGER
    st.markdown(
        f"""
        <div style="
            background:{CARD_BG}; border:1px solid {CARD_BORDER}; border-radius:10px;
            padding:14px 18px; margin-bottom:12px; box-shadow:{SHADOW};
        ">
            <div style="font-size:0.72rem; color:{TEXT_SECONDARY}; text-transform:uppercase;
                        letter-spacing:1px; margin-bottom:8px; font-weight:600;">{label}</div>
            <div style="font-size:1.4rem; font-weight:700; color:{TEXT_PRIMARY};
                        font-family:'JetBrains Mono',monospace; margin-bottom:8px;">
                {current:.1f}{suffix}
            </div>
            <div style="background:#1a2236;border-radius:4px;height:6px;overflow:hidden;">
                <div style="background:{bar_color};width:{pct * 100:.1f}%;height:100%;
                            border-radius:4px;transition:width 0.3s ease;"></div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def disclaimer_banner(text: str = "SIMULATION — not real operational data"):
    """Persistent simulation disclaimer with violet accent."""
    st.markdown(
        f"""
        <div style="
            background:rgba(139,92,246,0.12); border:1px solid #8B5CF6;
            border-radius:11px; padding:11px 16px; margin-bottom:14px;
            color:{TEXT}; font-size:0.84rem; text-align:center;
            font-weight:650; letter-spacing:0.3px; box-shadow:{SHADOW};">
            ⚠ {text}
        </div>
        """,
        unsafe_allow_html=True,
    )


def section_header(title: str, subtitle: str = ""):
    """Section header with optional subtitle."""
    sub_html = f'<span class="st-section-sub">{subtitle}</span>' if subtitle else ""
    st.markdown(
        f'<div class="st-section-title"><h3>{title}</h3>{sub_html}</div>',
        unsafe_allow_html=True,
    )
    st.markdown("---")


def skeleton_card():
    """Loading skeleton placeholder for async data."""
    st.markdown(
        '<div class="st-skeleton"></div>',
        unsafe_allow_html=True,
    )


def page_header(title: str, subtitle: str = "", machine: str | None = None):
    """Consistent page title block used by every view."""
    meta_bits = []
    if machine:
        meta_bits.append(machine)
    meta = f" · {' · '.join(meta_bits)}" if meta_bits else ""
    sub = f'<div class="st-page-sub">{subtitle}{meta}</div>' if subtitle or meta else ""
    st.markdown(
        f'<div class="st-page-title">{title}</div>{sub}',
        unsafe_allow_html=True,
    )
